### ISSUE TITLE
Nokia 6.1 / Nokia 6 (2018)

### ISSUE THREAD

**Issue by ja-som** [corcoran/android-device-names-registry#12]
Hi,
few days ago I bought the new Nokia 6.1 or Nokia 6 (2018), model number is TA-1043.
When I open "My device" it is recognized as Nokia 6 the 2017 version, so I tried to change it, but when I search for Nokia 6.1 or Nokia 6 (2018) the results are still only Nokia 6 and Nokia 7 Plus.

I wanted to edit the parsed.devices file, but I don´t understand few things there, so I leave it to you guys :)
E.g. **TA-1054 = Nokia 6**, but AFAIK it is the 2018 version and **Nokia 6.1 = Nokia 6.1**, but forum is Nokia 6 (2018):
https://forum.xda-developers.com/nokia-6-2018

I´m not sure whether they are all, but some Nokia 6.1 / Nokia 6 (2018) variants:
TA-1050, TA-1043, TA-1045, TA-1016, TA-1054

**Comment by TenSeventy7** [comment]
**Check this commit if this is correct.** https://github.com/corcoran/android-device-names-registry/pull/13

Do note that XDA Labs is not yet updated to include the Nokia 6 (2018).
I did research (I currently have no Nokia 6.1 with mine, still isn't available in my country), and tried verifying if TA-1043 and TA-1016 are Nokia 6.1s, **didn't yield any results.** So I temporarily skipped them.
